### ISSUE TITLE
Bootcamp grading rubric

### ISSUE THREAD

**Issue by mfisada** [fridells51/qbb2023-answers#1]
# Grading 

## Day 1 Homework 

| Exercise    | Task  | Grade |
| -------- | ------- | ------- |
| E1  | Printed out first, tenth, last days  | 0 |
| E2 | Calculated averages for all patients  | 0 | 
| E2    | Printed out first ten averages   | 0 |
| E3 | Printed out maximum | 0 | 
| E3 | Printed out minimum | 0 | 
| E4 | Printed out differences between patients | 0 |

## Day 2 Homework:  

| Exercise    | Task  | Grade |
| -------- | ------- | ------- |
| E1  | Plot female data | 1 |
| E1  | Add male data | 1 |
| E1  | Plotted two x male data | 0 |
| E1  | Added x axis label | 1 |
| E1  | Added y axis label | 1 |
| E1  | Labelled each line using a legend | 1 |
| E1  | Added plot title | 1 |

## Day 3 Homework: 

| Exercise    | Task  | Grade |
| -------- | ------- | ------- |
| E1  | `mean.py` calculates means | 1 |
| E2  | `mean_from_file.py` reads in file and calculates means | 1 |
| E3  | `mean_inflammation.py` contains function that calculates mean inflammation | 1 |
| E3  | `mean_inflammation.py` prints output | 1 |
| E4  | `difference_inflammation.py` contains function that calculates the difference in inflammation | 1 |
| E4  | `difference_inflammation.py` prints output | 1 | 

## Day 4 Homework: 

| Exercise    | Task  | Grade |
| -------- | ------- | ------- |
| E1  | Created a function to simulate WF | 1 |
| E1  | Find the number of generations to fixation | 1 |
| E1  | Plot of allele frequency over time | 0 |
| E2  | Plot of allele frequency over time for multiple alleles | 0 |
| E2  | Histogram of times to fixation | 0 |
| E3  | Plot of population size vs time to fixation | 0 |
| E3  | Plot of starting allele frequency vs time to fixation | 0 |
| E4  | Short written answers to three questions | 3 |

All worth 1 pt, except exercise 4, exercise 4, which is worth 3

**Comment by mfisada** [comment]
Nice work, Gus. Please submit your work from HW #1, plot 2*male data for HW #2, and submit all your graphs for HW #4.

**Comment by fridells51** [comment]
<img width="455" alt="Screenshot 2023-09-12 at 20 57 05" src="https://github.com/fridells51/qbb2023-answers/assets/63575426/aabfe91b-4f94-4652-bcd2-5612d2f0b049">

**Comment by fridells51** [comment]
Hey Matt, not sure if you didn't catch this, but I did plot the 2* male data.. This screenshot comes from the commit history. You can see that the male portion of the data in this curve is 2x what it was for the male + female data. I'll take the 0 on the question if this is not what you were looking for

**Comment by fridells51** [comment]
the rest is fixed.

**Comment by mfisada** [comment]
Hi Gus, thanks for the catch. I was only looking at your latest work, so I didn't see you plotted the 2*male in your history. For full credit, the female, male, and 2*male data all need to be on the same plot with a shared x-axis like in Fig 3A of (https://journals.plos.org/plosbiology/article?id=10.1371/journal.pbio.1000590). But you can obviously take the 0 as you said.

We also need the actual graphs from HW 4, not just the code. Did you push those too? I don't see them, but I do see the updated Wright-Fisher script and HW 1 (which looks good).

**Comment by fridells51** [comment]
I just pushed them, had them staged last night and forgot. Thanks for the reminder!

**Comment by mfisada** [comment]
I see three graphs for HW #4. Do you have the others? There should be a plot of population size vs. time to fixation, as well as a plot of starting allele frequency vs. time to fixation.

**Comment by fridells51** [comment]
I'm sorry, I named the file after a pattern that I was ignoring in my .gitignore. I fixed it. Thanks for the reminder!

**Comment by mfisada** [comment]
Thanks for the latest push, Gus, although it looks like you're still missing the plot of population size vs. time to fixation.

**Comment by fridells51** [comment]
fixed it. FOR REAL THIS TIME
